### ISSUE TITLE
meta community SAD

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#143] opened 2017-06-28 07:49 UTC
Hey @rueuntal can you please remind me why we sample with replacement from the treatment specific meta community SAD (i.e., extrapolated SAD) for the significance test on the aggregation and density effects rather than using the observed treatment specific SAD? Thanks!

**Comment by rueuntal** [comment] 2017-06-29 05:32
Hey @dmcglinn - sorry for the delay, I'm in LA for that workshop and will probably be slow in response until this weekend. I think the reasoning behind sampling from the projected metacommunity instead of observed SAD is that the observed SAD imposes a hard upper-bound, ie we can never get more species in simulation than observed. Given that the observed SAD is also a sample from the metacommunity, sampling from the metacommunity feels like a more reasonable choice. Does that make sense?

**Comment by dmcglinn** [comment] 2017-06-29 08:12
Thanks @rueuntal! I think the argument against using the meta SAD is that it makes additional assumptions about how to extrapolate the SAD which we know are flawed (i.e., random spatial structure). However, we must (?) scale up the SAD to test the treatment effect on the SAD because we sample across treatments; therefore, scaling up the SAD for the other tests is at least consistent with the SAD test. 

Also I'll just point out that somewhat counter intuitively for many datasets with large N the resampled SAD will typically have smaller S than observed S because we the meta SAD == obs SAD when N is large (based on our Chao method). 

@ngotelli @FelixMay @jmchase do you guys have an opinion of the importance of scaling up the SAD using the Chao et al 2014 approach (described by @ngotelli here https://github.com/MoBiodiv/mobr/issues/54#issuecomment-248607387)

**Comment by ngotelli** [comment] 2017-06-29 15:02
The problem is that if we simulate with random draws from a pooled assemblage, we can always generate a total S that is smaller than observed, but never one that is larger. So, this inevitably introduces a bias when the sampling is close or equal to the size of the original pooled sample. The Chao algorithm estimates missing species in the usual way, estimates their relative frequencies (of course we know they will be estimated to be rare), and then makes an adjustment to the relative frequencies of all the other species to account for this added tail of hidden diversity. That adjustment has almost no effect on the estimates of the common species but it does make the estimated frequencies of the observed rare species even rarer than before. Basically, the extra probability mass is shifted to the undetected fraction. But, as Dan notes, this kind of adjustment must assume a random distribution of species, so we can't use it with the spatial tests. This is the sort of option that I would include in the software, but not necessarily recommend (for now) if we can avoid it. Hope that helps!..

**Comment by dmcglinn** [comment] 2017-06-30 08:28
Thanks for your insight @ngotelli.  Yesterday I met with @FelixMay, @jmchase, and Shane Bolwes and they agree with the sentiment that using the observed SAD would be best but if we have to use it for the SAD test then it is best to be consistent across the tests simply for easing communicating in the paper exactly what our approach is. I'm going to investigate how big of a difference it really makes using the sensitivity tests if we use the observed SAD vs extrapolated SAD. 

One other point on the question of extrapolation is that our two Chao methods we use in the package do result in different extrapolated numbers of species which is problematic: 
```
# for the invaded forests
length(Jade::SpecDist(colSums(inv))$probability)
[1] 165
> vegan::estimateR(colSums(inv))
     S.obs    S.chao1   se.chao1      S.ACE     se.ACE 
 67.000000 150.250000  40.129922 150.972844   7.645155 
``` 
I suggest that we just use the extrapolated SAD approach to provide estimates of extrapolated S. Does this sound reasonable?

**Comment by ngotelli** [comment] 2017-06-30 13:55
Thanks Dan. I am not surprised that the vegan estimates are different. Over the years, Anne has developed many different tweaks to the Chao indices (especially for cases in which there are no singletons or doubletons). I am not sure if `vegan` has kept up with all of those changes.

Remember `Jade` is primarily going to affect the estimated relative abundance of the rare species. Unless the sample sizes in the analysis are very small or highly unbalanced among treatments, I would be surprised if it made too much of a difference. Your approach sounds reasonable. Thanks again for digging deep and doing all of this high-quality testing!

**Comment by rueuntal** [comment] 2017-07-23 21:28
@dmcglinn here is the comparison of using metacommunity SAD versus observed SAD in sensitivity analysis. The call to `Jade::SpecDist` in `permute_comm()` and `effect_SAD_discrete()` were replaced with frequency based on observed SAD for the latter. 

With metacommunity SAD: 

N | cv | sigma | SADTot | SADErr | NTot | NErr | AggTot | AggErr
-- | -- | -- | -- | -- | -- | -- | -- | --
1001 | NA | NA | 15000 | 1032 | 15000 | 103 | 8000 | 446
700 | NA | NA | 15000 | 1043 | 15000 | 15000 | 8000 | 426
800 | NA | NA | 15000 | 748 | 15000 | 15000 | 8000 | 418
900 | NA | NA | 15000 | 816 | 15000 | 12059 | 8000 | 477
NA | 0.5 | NA | 15000 | 14985 | 14989 | 0 | 8000 | 376
NA | 1 | NA | 15000 | 14374 | 14984 | 0 | 8000 | 410
NA | 1.5 | NA | 15000 | 8372 | 14985 | 0 | 8000 | 436
NA | NA | 0.02 | 15000 | 764 | 14930 | 0 | 8000 | 6343
NA | NA | 0.05 | 15000 | 719 | 14949 | 0 | 8000 | 5936
NA | NA | 0.1 | 15000 | 522 | 14943 | 0 | 8000 | 5444
NA | 1 | 0.05 | 15000 | 14456 | 14954 | 0 | 8000 | 6101
800 | NA | 0.05 | 15000 | 876 | 15000 | 14935 | 8000 | 6164
800 | 1 | NA | 15000 | 14664 | 15000 | 14999 | 8000 | 445
800 | 1 | 0.05 | 15000 | 14729 | 15000 | 14978 | 8000 | 6357

With observed SAD: 

N | cv | sigma | SADTot | SADErr | NTot | NErr | AggTot | AggErr
-- | -- | -- | -- | -- | -- | -- | -- | --
1001 | NA | NA | 15000 | 924 | 15000 | 313 | 8000 | 604
700 | NA | NA | 15000 | 1101 | 15000 | 15000 | 8000 | 604
800 | NA | NA | 15000 | 1065 | 15000 | 15000 | 8000 | 611
900 | NA | NA | 15000 | 1002 | 15000 | 14510 | 8000 | 589
NA | 0.5 | NA | 15000 | 14995 | 14986 | 0 | 8000 | 446
NA | 1 | NA | 15000 | 14604 | 14988 | 0 | 8000 | 469
NA | 1.5 | NA | 15000 | 9123 | 14986 | 0 | 8000 | 688
NA | NA | 0.02 | 15000 | 1096 | 14938 | 0 | 8000 | 6434
NA | NA | 0.05 | 15000 | 1068 | 14952 | 0 | 8000 | 6213
NA | NA | 0.1 | 15000 | 1118 | 14962 | 0 | 8000 | 5631
NA | 1 | 0.05 | 15000 | 14469 | 14951 | 0 | 8000 | 6276
800 | NA | 0.05 | 15000 | 1191 | 15000 | 14999 | 8000 | 6270
800 | 1 | NA | 15000 | 14772 | 15000 | 15000 | 8000 | 608
800 | 1 | 0.05 | 15000 | 14766 | 15000 | 14996 | 8000 | 6420

Based on eyeballing alone the two don't look much different.

**Comment by dmcglinn** [comment] 2017-07-24 01:57
Thanks for the hard work and the results @rueuntal . Just so I'm clear you turned off sampling from the meta SAD for all tests not just the aggr and density tests. Also when you say "frequency based on observed SAD" is that sampling with or without replacement? It sounds like sampling with replacement weighted by species observed frequencies which I don't think is quite what we wanted but appears to maybe not matter in the end.

**Comment by rueuntal** [comment] 2017-07-24 02:06
Hey @dmcglinn - I turned off the `SpecDist` function, which was only called by those two functions (plus one for the continuous case, which I didn't bother to change). That's all we need right?

By "frequency based on observed SAD", I meant turning the observed SAD into proportions, then sampling using those proportions as weights. So you are right it's sampling WITH replacement. Could you explain again why we may want the without replacement version?

**Comment by dmcglinn** [comment] 2017-07-24 02:20
Ok so based on that description of the changes you made means that your new tests (SAD, N, and aggr) never scaled up the SAD to the meta community SAD - thanks for clarifying! For some reason I remember that at least with respect to the SAD test we were having a lot of problems with bias in our tests when we didn't scale up the SAD - I guess those are not showing up now. Do you have a memory of this or did you chose to use the meta community SAD from a first principles argument? 

My reasoning for wanting sampling without replacement was to avoid the concern that you and @ngotelli both voiced of having null communities with fewer than S observed species. By sampling without replacement we could avoid this problem, but now that I'm thinking about it more carefully I'm realizing that this may cause some errors when the null community doesn't have exactly N observed individuals as is the case in the N effect test.

**Comment by rueuntal** [comment] 2017-07-24 02:33
Yes - I also remember us tweaking the SAD to get rid of bias. My collection is that was before we made the changes to the N-curve and lumped within-plot aggregation together with between-plot aggregation. Honestly we've made so many changes along the way it's hard to tell what made the difference... but yeah the bias no longer shows up, as far as I can see.

Ah I see what you mean. Nick's and my concern was indeed that the simulated communities would be constrained by observed S, which was why we preferred extrapolating to metacommunity. But I don't think that problem is addressed by sampling either WITH or WITHOUT replacement from the observe community. If we sample with replacement, the simulated communities may have lower S than observed. If we sample without replacement, the simulated communities would have exactly S species; this is still a constraint nonetheless, and it ignores the fact that the observed community is inevitably a random sample from a larger pool. So I kind of see both with and without replacement as suboptimal. However, I can also see that extrapolation makes additional assumptions that may not hold. Bottom line is extrapolation and sampling with replacement aren't that different :) If needed I can also run the thing again for sampling without replacement, but it will take another week or so.

**Comment by dmcglinn** [comment] 2017-07-24 03:28
Thanks for reaffirming my foggy memory - it has been a long road but we're almost there I think 👍  I don't think it is worth the time to check sampling without replacement - these results look good. One question I'd like to get your opinion on is that maybe there is very little difference between the meta SAD vs observed SAD tests because we're carrying out the sensitivity analyses on a simulated community with lots of individuals. In practice we will sometimes have very few individuals and in those cases the two SADs will diverge more. What are your thoughts here. Do we cover a large enough variation in N in our simulated communities that we can be sure this isn't an issue? Thanks!

**Comment by rueuntal** [comment] 2017-07-24 03:43
You are absolutely right - the communities we simulated are "standard" ones, with high N, nice lognormal shape, almost always some singletons but not overwhelming. We've never tested scenarios as we saw in empirical data sometimes where S_observed is 10 and S_meta could be estimated to be 100+. Naively I'd expect sampling works better than extrapolation in that scenario, but it may be worth testing out. What do you think?

**Comment by dmcglinn** [comment] 2017-07-24 19:10
That's a good point. Well I think we have our answer - let's remove any upscaling of the SAD in the name of  parsimony despite a priori arguments that it seems like a better approach in theory. Does this sound reasonable to you at this point?

**Comment by ngotelli** [comment] 2017-07-24 19:14
That sounds fine to me. Simple, clear, and limited is better than complex, fuzzy, and comprehensive.


N.


________________________________

**Comment by rueuntal** [comment] 2017-07-24 20:43
Sounds good to me! I will submit a PR for the code.

**Closed** 2017-07-25 11:57 UTC
Labels: question
